# Generated by Django 4.2.30 on 2026-06-07 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_str', models.CharField(max_length=20)),
                ('sales', models.DecimalField(decimal_places=2, max_digits=15)),
                ('debt_to_equity', models.DecimalField(decimal_places=4, max_digits=10)),
                ('anomaly_reason', models.TextField()),
            ],
            options={
                'db_table': 'ml_anomaly_flag',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyScore',
            fields=[
                ('symbol', models.OneToOneField(db_column='symbol', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='companies.dimcompany')),
                ('health_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('health_label', models.CharField(max_length=20)),
                ('profitability_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('growth_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('solvency_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('liquidity_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('efficiency_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('scale_score', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'ml_company_score',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PeerGroup',
            fields=[
                ('symbol', models.OneToOneField(db_column='symbol', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='peer_group', serialize=False, to='companies.dimcompany')),
            ],
            options={
                'db_table': 'ml_peer_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SalesForecast',
            fields=[
                ('symbol', models.OneToOneField(db_column='symbol', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='companies.dimcompany')),
                ('current_year', models.IntegerField()),
                ('current_sales', models.DecimalField(decimal_places=2, max_digits=15)),
                ('forecast_year', models.IntegerField()),
                ('forecasted_sales', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'db_table': 'ml_sales_forecast',
                'managed': False,
            },
        ),
    ]
