# Generated by Django 4.2.30 on 2026-06-07 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DimCompany',
            fields=[
                ('symbol', models.CharField(db_column='symbol', max_length=50, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('company_logo', models.TextField(blank=True, null=True)),
                ('chart_link', models.TextField(blank=True, null=True)),
                ('about_company', models.TextField(blank=True, null=True)),
                ('website', models.TextField(blank=True, null=True)),
                ('nse_profile', models.TextField(blank=True, null=True)),
                ('bse_profile', models.TextField(blank=True, null=True)),
                ('face_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('book_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('roce_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('roe_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_banking', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'dim_company',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimSector',
            fields=[
                ('sector_name', models.CharField(db_column='sector_name', max_length=100, primary_key=True, serialize=False)),
                ('sector_desc', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dim_sector',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimYear',
            fields=[
                ('year_str', models.CharField(db_column='year_str', max_length=20, primary_key=True, serialize=False)),
                ('sort_order', models.IntegerField()),
                ('is_ttm', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'dim_year',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FactAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compounded_sales_growth', models.TextField(blank=True, null=True)),
                ('compounded_profit_growth', models.TextField(blank=True, null=True)),
                ('stock_price_cagr', models.TextField(blank=True, null=True)),
                ('roe', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fact_analysis',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FactBalancesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equity_capital', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('reserves', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('borrowings', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('other_liabilities', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_liabilities', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('fixed_assets', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('cwip', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('investments', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('other_assets', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_assets', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('debt_to_equity', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'fact_balancesheet',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FactCashflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operating_activity', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('investing_activity', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('financing_activity', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('net_cash_flow', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('free_cash_flow', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
            ],
            options={
                'db_table': 'fact_cashflow',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FactDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_int', models.IntegerField()),
                ('annual_report_url', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fact_documents',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FactProfitAndLoss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('expenses', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('operating_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('opm_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('other_income', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('interest', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('depreciation', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('profit_before_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('tax_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('net_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('eps', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dividend_payout', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('net_profit_margin_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'fact_profitandloss',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FactProsAndCons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pros', models.TextField(blank=True, null=True)),
                ('cons', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fact_prosandcons',
                'managed': False,
            },
        ),
    ]
